server:
  port: 8081
spring:
  application:
    name: sw-dada
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dada?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    user_name: root
    password: 1111
  redis:
    host: 124.221.54.150
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    password: redispass123
    database: 2
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  profiles:
    active: local
logging:
  level:
    com.snwolf: debug
mybatis-plus:
  type-aliases-package: com.snwolf.dada.domain.entity # 别名扫描包